
# Stage 1

FROM node:14-alpine as build-step


RUN npm install -g @angular/cli@10


WORKDIR /app

COPY package.json /app

RUN yarn install 


RUN npm install -D typescript@4.0.2

COPY . /app

#♣CMD ng serve --host 0.0.0.0



RUN npm run ng build host --prod

# Stage 2

FROM nginx:1.17.1-alpine

COPY --from=build-step /app/dist/pds2 /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
EXPOSE 4200